ai:
  api_base_url: "https://api.deepseek.com"
  api_key_env_var: "deepseek_api_key"

  model: "deepseek-chat" # DeepSeek-V3
#  model: "deepseek-reasoner" # DeepSeek-R1

  system_content: "You are a helpful assistant"
#  system_content: "你是一个诗人"

  # Possible values: > 1
  # 介于 1 到 8192 间的整数，限制一次请求中模型生成 completion 的最大 token 数。输入 token 和输出 token 的总长度受模型的上下文长度的限制。
  # 如未指定 max_tokens参数，默认使用 4096。
  # ---------------------------
  # token 是模型用来表示自然语言文本的基本单位，也是计费单元，可以直观的理解为“字”或“词”；
  # 通常 1 个中文词语、1 个英文单词、1 个数字或 1 个符号计为 1 个 token。
  # 一般情况下模型中 token 和字数的换算比例大致如下：
  # 1 个英文字符 ≈ 0.3 个 token。
  # 1 个中文字符 ≈ 0.6 个 token。
  # 但因为不同模型的分词不同，所以换算比例也存在差异，每一次实际处理 token 数量以模型返回为准，可以从返回结果的 usage 中查看。
  max_tokens: 500 # default: 4K

  # Possible values: <= 2
  # Default value: 1
  # 采样温度，介于 0 和 2 之间。
  # 更高的值，如 0.8，会使输出更随机，而更低的值，如 0.2，会使其更加集中和确定。
  # 我们通常建议可以更改这个值或者更改 top_p，但不建议同时对两者进行修改。
  ## 代码生成/数学解题: 0.0
  ## 数据抽取/分析: 1.0 (default)
  ## 通用对话: 1.3
  ## 翻译: 1.3
  ## 创意类写作/诗歌创作: 1.5
  temperature: 1

  # Possible values: <= 1
  # Default value: 1
  # 作为调节采样温度的替代方案，模型会考虑前 top_p 概率的 token 的结果。
  # 所以 0.1 就意味着只有包括在最高 10% 概率中的 token 会被考虑。
  # 我们通常建议修改这个值或者更改 temperature，但不建议同时对两者进行修改。
  # 越大(1): 内容发散,较有创意
  # 越小(0.5): 内容集中,较确定
  top_p: 1

  # default: 1, only n=1 is supported by DeepSeek, other values are supported by OpenAI
  # 模型对每个输入生成的回答数量。设置为n就会生成n个独立的回答。
  # 用来获取多个回答，便于选择或综合。
  n: 1

  # Possible values: >= -2 and <= 2
  # Default value: 0
  # 介于 -2.0 和 2.0 之间的数字。如果该值为正，那么新token会根据其是否已在已有文本中出现受到相应的惩罚，从而增加模型谈论新主题的可能性。
  # 影响模型生成新主题内容的倾向, 较高的值鼓励模型生成前面未出现过的新内容。
  # 用法: 用来避免重复内容，增加多样性。
  presence_penalty: 0

  # Possible values: >= -2 and <= 2
  # Default value: 0
  # 介于 -2.0 和 2.0 之间的数字。如果该值为正，那么新 token 会根据其在已有文本中的出现频率受到相应的惩罚，降低模型重复相同内容的可能性。
  # 影响模型是否重复使用某些词或短语。较高的值会减少模型重复使用某些词或短语的频率。
  # 用法: 用来减少重复词语，提高输出的流畅度和多样性。不罗嗦。
  frequency_penalty: 0

  # AI默认的输出格式markdown
  # 设置 response_format 参数为 {'type': 'json_object'}。
  # 用户传入的 system 或 user prompt 中必须含有 json 字样，并给出希望模型输出的 JSON 格式的样例，以指导模型来输出合法 JSON。
  # 需要合理设置 max_tokens 参数，防止 JSON 字符串被中途截断。
  # 在使用 JSON Output 功能时，API 有概率会返回空的 content。我们正在积极优化该问题，您可以尝试修改 prompt 以缓解此类问题。
#  response_format: "json_object"
  response_format: "text"

  # seed参数用于设置随机种子，以确保相同的输入在多次调用时返回一致的结果。这对于需要稳定输出的场景（如测试或生产环境）非常有用
  # 默认值：如果不设置seed（即seed=None），每次调用可能会返回不同的结果。
  # 适用场景：适合需要可重复性结果的任务，例如测试、调试或生成固定内容。
  # 限制：即使设置了相同的种子，不同模型或不同版本可能仍会产生略微不同的结果。
  seed:
#  seed: 42
